# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 18:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('note', models.CharField(max_length=500)),
                ('avg_preparation_time', models.DurationField(verbose_name='Average preparation time.')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_number', models.IntegerField(verbose_name='Daily Number')),
                ('open_time', models.DateTimeField(verbose_name='Open Time')),
                ('close_time', models.DateTimeField(verbose_name='Close Time')),
            ],
        ),
        migrations.CreateModel(
            name='OrderContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='queue.Menu', verbose_name='Menu Item')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='queue.Order')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.IntegerField()),
            ],
        ),
    ]
