# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 05:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('queue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='content_completed',
            field=models.BooleanField(default=False, verbose_name='Content Completed'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='supplement_completed',
            field=models.BooleanField(default=False, verbose_name='Supplement Completed'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordercontent',
            name='finish_timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start Timestamp'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordercontent',
            name='staff_maker',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='queue.Staff', verbose_name='Staff Maker'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordercontent',
            name='start_timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start Timestamp'),
            preserve_default=False,
        ),
    ]
