# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 05:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue', '0002_auto_20170523_0531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordercontent',
            name='finish_timestamp',
            field=models.DateTimeField(verbose_name='Finish Timestamp'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='category',
            field=models.CharField(choices=[('Csh', 'Cashier'), ('Ck', 'Cook'), ('Op', 'Operator')], default='Cashier', max_length=3),
        ),
    ]
