# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue', '0003_auto_20170523_0550'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
