# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 18:59
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue', '0004_menu_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.FloatField(default=0, editable=False, validators=[django.core.validators.MinValueValidator(0, "Total can't be negative!")]),
        ),
        migrations.AddField(
            model_name='staff',
            name='available',
            field=models.BooleanField(default='False'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='avg_preparation_time',
            field=models.DurationField(editable=False, verbose_name='Average preparation time.'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='price',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0, "Price can't be negative!")]),
        ),
        migrations.AlterField(
            model_name='order',
            name='daily_number',
            field=models.IntegerField(unique_for_date=True, verbose_name='Daily Number'),
        ),
    ]
