# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 20:35
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue', '0005_auto_20170524_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='avg_preparation_time',
            field=models.DurationField(verbose_name='Average preparation time.'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0, "Total can't be negative!")]),
        ),
    ]
