# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 15:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('queue', '0006_auto_20170524_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='close_time',
            field=models.DateTimeField(null=True, verbose_name='Close Time'),
        ),
        migrations.AlterField(
            model_name='order',
            name='content_completed',
            field=models.BooleanField(default=False, verbose_name='Content Completed'),
        ),
        migrations.AlterField(
            model_name='order',
            name='supplement_completed',
            field=models.BooleanField(default=False, verbose_name='Supplement Completed'),
        ),
        migrations.AlterField(
            model_name='ordercontent',
            name='finish_timestamp',
            field=models.DateTimeField(null=True, verbose_name='Finish Timestamp'),
        ),
        migrations.AlterField(
            model_name='ordercontent',
            name='staff_maker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='queue.Staff', verbose_name='Staff Maker'),
        ),
        migrations.AlterField(
            model_name='ordercontent',
            name='start_timestamp',
            field=models.DateTimeField(null=True, verbose_name='Start Timestamp'),
        ),
    ]
