# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-20 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue', '0007_auto_20170525_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_canceled',
            field=models.BooleanField(default=False, verbose_name='Is canceled'),
        ),
        migrations.AddField(
            model_name='ordercontent',
            name='is_canceled',
            field=models.BooleanField(default=False, verbose_name='Is canceled'),
        ),
        migrations.AddField(
            model_name='ordercontent',
            name='is_in_grill',
            field=models.BooleanField(default=False, verbose_name='Is in grill'),
        ),
        migrations.AddField(
            model_name='ordercontent',
            name='note',
            field=models.CharField(default='', max_length=500),
        ),
    ]
