# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-24 05:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue', '0017_ordercontent_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_grilling',
            field=models.BooleanField(default=False, verbose_name='Is Grilling'),
        ),
    ]
